<a href="https://colab.research.google.com/github/vitormiro/estatistica_ppger_ufc/blob/main/python_fundamentos_5_numpy_p1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

O **NumPy**, abreviatura para *Numerical Python* (Python Numérico), é uma biblioteca Python que fornece um grande conjunto de funções e operações para executar facilmente cálculos numéricos.

A estrutura de dados mais importante que o NumPy fornece é um objeto poderoso, um tipo de *array* (arranjo), chamada **ndarray**. 

No Python, um array é um objeto semelhante a uma lista, mas é uma estrutura de dados que armazena informações de um mesmo tipo.

Podemos pensar em um array em NumPy como uma tabela multidimensional de elementos do mesmo tipo, indexados por uma tupla de inteiros positivos. 
A vantagem dos arrays (ndarrays) é a possibilidade de realizar operações matemáticas em blocos inteiros de dados usando uma sintaxe semelhante às operações com elementos escalares.

[Documentação do Numpy](https://numpy.org/doc/stable/contents.html#)

### Recursos do NumPy





In [ ]:
# Se for necessário, primeiro devemos instalar o NumPy (retirar o # da linha abaixo antes de executar)
#!pip install numpy

# E importar o NumPy com o alias 'np'
import numpy as np

Vamos criar um array


In [ ]:
# criando um array de números inteiros
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

Vamos criar um array convertendo uma lista

In [ ]:
# cria uma lista
x = [1, 4, 2, 5, 3]
x

[1, 4, 2, 5, 3]

In [ ]:
# converter para array
x = np.array(x)
x

array([1, 4, 2, 5, 3])

In [ ]:
type(x)

numpy.ndarray

In [ ]:
# Soma
x.sum()

15

In [ ]:
# valor mínimo
x.min()

1

In [ ]:
# valor máximo
x.max()

5

In [ ]:
# soma de arrays (elemento por elemento)
# Exemplo: notas de duas provas
nota1 = np.array([2.5, 4, 3.5, 3, 4])
nota2 = np.array([3.5, 3.5, 3.5, 4, 4.5])
nota = nota1 + nota2
nota

array([6. , 7.5, 7. , 7. , 8.5])

In [ ]:
# soma com escalar
notaf = nota + 0.5
notaf

array([6.5, 8. , 7.5, 7.5, 9. ])

In [ ]:
# operação de comparação
aprovados = notaf >=7
aprovados

array([False,  True,  True,  True,  True])

In [ ]:
# multiplicação de arrays (elemento por elemento)
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])
prod = x * y
prod

array([ 5, 12, 21, 32])

In [ ]:
# multiplicação por um escalar
x2 = x * 2
x2

array([2, 4, 6, 8])

Vejamos algumas operações de interesse no nosso curso (Estatística Aplicada).

**Produto escalar de dois vetores**

$$\sum_{i=0}^{n-1} x_i * y_i = x_0*y_0 + x_1*y_1 + \dots + x_{n-1}*y_{n-1}$$



In [ ]:
# produto escalar
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])
pxy = np.dot(x, y)
pxy

70

**Soma dos quadrados**

$$\sum_{i=0}^{n-1} x_i^2 = x_0^2 + x_1^2 + \dots + x_{n-1}^2$$


In [ ]:
# soma dos quadrados
xquad = np.dot(x, x)
xquad

30

## Operações com matrizes

Sobre o [numpy.matrix](https://numpy.org/doc/stable/reference/generated/numpy.matrix.html?highlight=matrix#numpy.matrix).


In [ ]:
# criar matriz
A = np.matrix([[1, 2, 3, 4],
               [5, 6, 7, 8]])
A

matrix([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [ ]:
type(A)

numpy.matrix

Soma de matrizes
$$ 
\begin{pmatrix} a_{11} & a_{12} & a_{13}\\ a_{21} & a_{22} & a_{23} \\ a_{31} & a_{32} & a_{33}\end{pmatrix} + 
\begin{pmatrix} b_{11} & b_{12} & b_{13}\\ b_{21} & b_{22} & b_{23} \\ b_{31} & b_{32} & b_{33}\end{pmatrix} = 
\begin{pmatrix} a_{11}+b_{11} & a_{12}+b_{12} & a_{13}+b_{13}\\ a_{21}+b_{21} & a_{22}+b_{22} & a_{23}+b_{23} \\ a_{31}+b_{31} & a_{32}+b_{32} & a_{33}+b_{33}\end{pmatrix}
 $$

In [ ]:
# soma de matrizes
A = np.matrix([[1, 2, 3, 4], 
               [5, 6, 7, 8]])
B = np.matrix([[1, 2, 3, 4], 
               [5, 6, 7, 8]])

S = A + B
S

matrix([[ 2,  4,  6,  8],
        [10, 12, 14, 16]])

Transposta
$$ \begin{pmatrix} a_{11} & a_{12} & a_{13}\\ a_{21} & a_{22} & a_{23} \\ a_{31} & a_{32} & a_{33} \end{pmatrix}^T = 
\begin{pmatrix} a_{11} & a_{21} & a_{31}\\ a_{21} & a_{22} & a_{23} \\ a_{13} & a_{23} & a_{33} \end{pmatrix} $$

In [ ]:
# Transposta
A.T

matrix([[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]])

Multiplicação de matrizes
$$ 
\begin{pmatrix} a_{11} & a_{12} & a_{13}\\ a_{21} & a_{22} & a_{23} \end{pmatrix}_{2\times3} * 
\begin{pmatrix} b_{11} & b_{12} \\ b_{21} & b_{22} \\ b_{31} & b_{32} \end{pmatrix}_{3\times2} = 
\begin{pmatrix} a_{11}b_{11}+a_{12}b_{21}+a_{13}b_{31} & a_{11}b_{12}+a_{12}b_{22}+a_{13}b_{32} \\ 
a_{21}b_{11}+a_{22}b_{21}+a_{23}b_{31} & a_{21}b_{12}+a_{22}b_{22}+a_{23}b_{32}  \end{pmatrix}_{2\times2} 
$$

In [ ]:
# multiplicação
P = A*B

ValueError: ignored

Temos um erro por `B` foi definida como uma matriz (2 X 4). Devemos fazer a transposta de `B`.

In [ ]:
Bt = B.T
Bt

matrix([[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]])

In [ ]:
P = A*Bt
P

matrix([[ 30,  70],
        [ 70, 174]])

### Manipulação de Arrays

Vamos usar um **gerador de números aleatórios** do NumPy - `np.random`.

Sobre o [`np.random`](https://numpy.org/doc/1.16/reference/routines.random.html).

Também usaremos uma "semente aleatória" para garantir a geração dos mesmos valores.


In [ ]:
np.random.seed(1)  # "seed" para gerar os mesmos valores

x1 = np.random.randint(10, size=3)  # array de 1 dimensão
x2 = np.random.randint(10, size=(3, 3))  # array de 2 dimensões
x3 = np.random.randint(10, size=(3, 2, 2))  # array de 3 dimensões

In [ ]:
# mostrar x1
x1

array([5, 8, 9])

In [ ]:
# mostrar x2
x2

array([[5, 0, 0],
       [1, 7, 6],
       [9, 2, 4]])

In [ ]:
# mostrar x3
x3

array([[[5, 2],
        [4, 2]],

       [[4, 7],
        [7, 9]],

       [[1, 7],
        [0, 6]]])

**Acessando elementos em um array**

In [ ]:
x1[0]

5

In [ ]:
x2[2,2]

4

In [ ]:
x2[0,0]

5

In [ ]:
x3[0, 0, 0]

5

In [ ]:
x3[1]

array([[4, 7],
       [7, 9]])

**Modificando elementos**


In [ ]:
x2[0, 0] = 12
x2

array([[12,  0,  0],
       [ 1,  7,  6],
       [ 9,  2,  4]])

In [ ]:
x3[2, 1, 1] = 20
x3[2]

array([[ 1,  7],
       [ 0, 20]])

**Fatiamento**

`x[start:stop:step]`


In [ ]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[:5]  # primeiros 5 elementos

array([0, 1, 2, 3, 4])

In [ ]:
x[5:]  # elementos após o índice 5

array([5, 6, 7, 8, 9])

In [ ]:
x[4:7]  # sub-array

array([4, 5, 6])

In [ ]:
x[0:8:2]

array([0, 2, 4, 6])

**Remodelagem de um array**

A maneira mais fácil de fazer isso é com um método `reshape`.


In [ ]:
y = np.arange(1, 10)
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
y = np.arange(1, 10).reshape((3, 3))
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
y = np.arange(0,20,2).reshape((2, 5))
y

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

Observe que, para que isso funcione, o tamanho do array inicial deve corresponder ao tamanho da matriz remodelada. 

**Concatenação**

A concatenação ou junção de dois arrays no NumPy é realizada, principalmente, com o emprego das rotinas `np.concatenate`, `np.vstack` e `np.hstack`.

O `np.concatenate` usa uma tupla ou lista de matrizes como seu primeiro argumento:

In [ ]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

Usando o `np.vstack` (concatenação vertical)

In [ ]:
x = np.array([1, 2, 3])
w = np.array([[9, 8, 7], [6, 5, 4]])

np.vstack([x, w])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

Usando o `np.hstack` (concatenação horizontal)

In [ ]:
x = np.array([[3],[2]])
w = np.array([[9, 8, 7], [6, 5, 4]])

print(x)
print(w)

np.hstack([w, x])

[[3]
 [2]]
[[9 8 7]
 [6 5 4]]


array([[9, 8, 7, 3],
       [6, 5, 4, 2]])

**Separação**

O oposto da concatenação é a separação, que é implementada pelas funções `np.split`, `np.hsplit` e `np.vsplit`.

In [ ]:
x = np.arange(9.0)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [ ]:
np.split(x, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [ ]:
x = [1, 2, 3, 4, 5, 6, 7, 8]
x1, x2 = np.split(x, [4])
print(x1, x2)

[1 2 3 4] [5 6 7 8]


In [ ]:
A = np.arange(16).reshape(4,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.hsplit(A, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [ ]:
A1, A2 = np.hsplit(A, 2)
print('A1 =', A1)
print('A2 =', A2)

A1 = [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
A2 = [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [ ]:
B = np.arange(12).reshape(4,3)
B

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
np.vsplit(B, 2)

[array([[0, 1, 2],
        [3, 4, 5]]), array([[ 6,  7,  8],
        [ 9, 10, 11]])]